# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tamvm/Projects/misc/blog/fbthrift

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tamvm/Projects/misc/blog/fbthrift

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tamvm/Projects/misc/blog/fbthrift/CMakeFiles /home/tamvm/Projects/misc/blog/fbthrift/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tamvm/Projects/misc/blog/fbthrift/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fbthrift_ex

# Build rule for target.
fbthrift_ex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fbthrift_ex
.PHONY : fbthrift_ex

# fast build rule for target.
fbthrift_ex/fast:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/build
.PHONY : fbthrift_ex/fast

#=============================================================================
# Target rules for targets named thrift

# Build rule for target.
thrift: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thrift
.PHONY : thrift

# fast build rule for target.
thrift/fast:
	$(MAKE) -f CMakeFiles/thrift.dir/build.make CMakeFiles/thrift.dir/build
.PHONY : thrift/fast

gen-cpp2/ExampleService.o: gen-cpp2/ExampleService.cpp.o

.PHONY : gen-cpp2/ExampleService.o

# target to build an object file
gen-cpp2/ExampleService.cpp.o:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/ExampleService.cpp.o
.PHONY : gen-cpp2/ExampleService.cpp.o

gen-cpp2/ExampleService.i: gen-cpp2/ExampleService.cpp.i

.PHONY : gen-cpp2/ExampleService.i

# target to preprocess a source file
gen-cpp2/ExampleService.cpp.i:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/ExampleService.cpp.i
.PHONY : gen-cpp2/ExampleService.cpp.i

gen-cpp2/ExampleService.s: gen-cpp2/ExampleService.cpp.s

.PHONY : gen-cpp2/ExampleService.s

# target to generate assembly for a file
gen-cpp2/ExampleService.cpp.s:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/ExampleService.cpp.s
.PHONY : gen-cpp2/ExampleService.cpp.s

gen-cpp2/ExampleServiceAsyncClient.o: gen-cpp2/ExampleServiceAsyncClient.cpp.o

.PHONY : gen-cpp2/ExampleServiceAsyncClient.o

# target to build an object file
gen-cpp2/ExampleServiceAsyncClient.cpp.o:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/ExampleServiceAsyncClient.cpp.o
.PHONY : gen-cpp2/ExampleServiceAsyncClient.cpp.o

gen-cpp2/ExampleServiceAsyncClient.i: gen-cpp2/ExampleServiceAsyncClient.cpp.i

.PHONY : gen-cpp2/ExampleServiceAsyncClient.i

# target to preprocess a source file
gen-cpp2/ExampleServiceAsyncClient.cpp.i:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/ExampleServiceAsyncClient.cpp.i
.PHONY : gen-cpp2/ExampleServiceAsyncClient.cpp.i

gen-cpp2/ExampleServiceAsyncClient.s: gen-cpp2/ExampleServiceAsyncClient.cpp.s

.PHONY : gen-cpp2/ExampleServiceAsyncClient.s

# target to generate assembly for a file
gen-cpp2/ExampleServiceAsyncClient.cpp.s:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/ExampleServiceAsyncClient.cpp.s
.PHONY : gen-cpp2/ExampleServiceAsyncClient.cpp.s

gen-cpp2/ExampleService_processmap_binary.o: gen-cpp2/ExampleService_processmap_binary.cpp.o

.PHONY : gen-cpp2/ExampleService_processmap_binary.o

# target to build an object file
gen-cpp2/ExampleService_processmap_binary.cpp.o:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/ExampleService_processmap_binary.cpp.o
.PHONY : gen-cpp2/ExampleService_processmap_binary.cpp.o

gen-cpp2/ExampleService_processmap_binary.i: gen-cpp2/ExampleService_processmap_binary.cpp.i

.PHONY : gen-cpp2/ExampleService_processmap_binary.i

# target to preprocess a source file
gen-cpp2/ExampleService_processmap_binary.cpp.i:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/ExampleService_processmap_binary.cpp.i
.PHONY : gen-cpp2/ExampleService_processmap_binary.cpp.i

gen-cpp2/ExampleService_processmap_binary.s: gen-cpp2/ExampleService_processmap_binary.cpp.s

.PHONY : gen-cpp2/ExampleService_processmap_binary.s

# target to generate assembly for a file
gen-cpp2/ExampleService_processmap_binary.cpp.s:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/ExampleService_processmap_binary.cpp.s
.PHONY : gen-cpp2/ExampleService_processmap_binary.cpp.s

gen-cpp2/ExampleService_processmap_compact.o: gen-cpp2/ExampleService_processmap_compact.cpp.o

.PHONY : gen-cpp2/ExampleService_processmap_compact.o

# target to build an object file
gen-cpp2/ExampleService_processmap_compact.cpp.o:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/ExampleService_processmap_compact.cpp.o
.PHONY : gen-cpp2/ExampleService_processmap_compact.cpp.o

gen-cpp2/ExampleService_processmap_compact.i: gen-cpp2/ExampleService_processmap_compact.cpp.i

.PHONY : gen-cpp2/ExampleService_processmap_compact.i

# target to preprocess a source file
gen-cpp2/ExampleService_processmap_compact.cpp.i:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/ExampleService_processmap_compact.cpp.i
.PHONY : gen-cpp2/ExampleService_processmap_compact.cpp.i

gen-cpp2/ExampleService_processmap_compact.s: gen-cpp2/ExampleService_processmap_compact.cpp.s

.PHONY : gen-cpp2/ExampleService_processmap_compact.s

# target to generate assembly for a file
gen-cpp2/ExampleService_processmap_compact.cpp.s:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/ExampleService_processmap_compact.cpp.s
.PHONY : gen-cpp2/ExampleService_processmap_compact.cpp.s

gen-cpp2/example_constants.o: gen-cpp2/example_constants.cpp.o

.PHONY : gen-cpp2/example_constants.o

# target to build an object file
gen-cpp2/example_constants.cpp.o:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/example_constants.cpp.o
.PHONY : gen-cpp2/example_constants.cpp.o

gen-cpp2/example_constants.i: gen-cpp2/example_constants.cpp.i

.PHONY : gen-cpp2/example_constants.i

# target to preprocess a source file
gen-cpp2/example_constants.cpp.i:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/example_constants.cpp.i
.PHONY : gen-cpp2/example_constants.cpp.i

gen-cpp2/example_constants.s: gen-cpp2/example_constants.cpp.s

.PHONY : gen-cpp2/example_constants.s

# target to generate assembly for a file
gen-cpp2/example_constants.cpp.s:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/example_constants.cpp.s
.PHONY : gen-cpp2/example_constants.cpp.s

gen-cpp2/example_data.o: gen-cpp2/example_data.cpp.o

.PHONY : gen-cpp2/example_data.o

# target to build an object file
gen-cpp2/example_data.cpp.o:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/example_data.cpp.o
.PHONY : gen-cpp2/example_data.cpp.o

gen-cpp2/example_data.i: gen-cpp2/example_data.cpp.i

.PHONY : gen-cpp2/example_data.i

# target to preprocess a source file
gen-cpp2/example_data.cpp.i:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/example_data.cpp.i
.PHONY : gen-cpp2/example_data.cpp.i

gen-cpp2/example_data.s: gen-cpp2/example_data.cpp.s

.PHONY : gen-cpp2/example_data.s

# target to generate assembly for a file
gen-cpp2/example_data.cpp.s:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/example_data.cpp.s
.PHONY : gen-cpp2/example_data.cpp.s

gen-cpp2/example_types.o: gen-cpp2/example_types.cpp.o

.PHONY : gen-cpp2/example_types.o

# target to build an object file
gen-cpp2/example_types.cpp.o:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/example_types.cpp.o
.PHONY : gen-cpp2/example_types.cpp.o

gen-cpp2/example_types.i: gen-cpp2/example_types.cpp.i

.PHONY : gen-cpp2/example_types.i

# target to preprocess a source file
gen-cpp2/example_types.cpp.i:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/example_types.cpp.i
.PHONY : gen-cpp2/example_types.cpp.i

gen-cpp2/example_types.s: gen-cpp2/example_types.cpp.s

.PHONY : gen-cpp2/example_types.s

# target to generate assembly for a file
gen-cpp2/example_types.cpp.s:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/gen-cpp2/example_types.cpp.s
.PHONY : gen-cpp2/example_types.cpp.s

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/fbthrift_ex.dir/build.make CMakeFiles/fbthrift_ex.dir/main.cc.s
.PHONY : main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... fbthrift_ex"
	@echo "... thrift"
	@echo "... gen-cpp2/ExampleService.o"
	@echo "... gen-cpp2/ExampleService.i"
	@echo "... gen-cpp2/ExampleService.s"
	@echo "... gen-cpp2/ExampleServiceAsyncClient.o"
	@echo "... gen-cpp2/ExampleServiceAsyncClient.i"
	@echo "... gen-cpp2/ExampleServiceAsyncClient.s"
	@echo "... gen-cpp2/ExampleService_processmap_binary.o"
	@echo "... gen-cpp2/ExampleService_processmap_binary.i"
	@echo "... gen-cpp2/ExampleService_processmap_binary.s"
	@echo "... gen-cpp2/ExampleService_processmap_compact.o"
	@echo "... gen-cpp2/ExampleService_processmap_compact.i"
	@echo "... gen-cpp2/ExampleService_processmap_compact.s"
	@echo "... gen-cpp2/example_constants.o"
	@echo "... gen-cpp2/example_constants.i"
	@echo "... gen-cpp2/example_constants.s"
	@echo "... gen-cpp2/example_data.o"
	@echo "... gen-cpp2/example_data.i"
	@echo "... gen-cpp2/example_data.s"
	@echo "... gen-cpp2/example_types.o"
	@echo "... gen-cpp2/example_types.i"
	@echo "... gen-cpp2/example_types.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

